version: '3.8'

services:
  stock-analyzer:
    build: .
    ports:
      - "8888:8888"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - .:/app
    restart: unless-stopped
